#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# run Prettier on staged files
echo "Running Prettier.."
./node_modules/.bin/prettier $STAGED_FILES --ignore-unknown --write

# add files auto-fixed by prettier
git add -f $STAGED_FILES


# run tests related to staged files
echo "Running Tests"
./node_modules/.bin/jest --bail --findRelatedTests $STAGED_FILES --passWithNoTests
JEST_EXIT_CODE=$?

# check jest exit code
if [ $JEST_EXIT_CODE -ne 0 ]; then
    echo "Tests have failures! Cannot commit!"
    exit 1
else
    echo "test all good..👍"
fi

# return 0-exit code
echo "🎉 All good 🎉"
exit 0